name: SViz
markdown: redcarpet
pygments: true

baseurl: /sviz

visualizations:
  - name: Progress
    path: progress
  - name: Course Donuts
    path: course
  - name: Evaluation
    path: evaluation
  - name: Statistics
    path: statistics