name: SViz
markdown: redcarpet
pygments: true

encoding: utf-8

baseurl: /sviz

visualizations:
  - name: Progress
    path: progress
  - name: Overall Statistics
    path: statistics2
  - name: Course Donuts
    path: course
  - name: Histogram
    path: histogram
  - name: Evaluation Statistics
    path: statistics
  - name: BoxPlot
    path: boxplot
  - name: Sunburst
    path: sunburst
  - name: Bubbles
    path: bubbles